artifact_location: /Users/zahra/ml_project/mlflow/855227014794509726
creation_time: 1776716133473
experiment_id: '855227014794509726'
last_update_time: 1776716133473
lifecycle_stage: active
name: airbnb-price-prediction
trace_location: null
workspace: default
